### ISSUE TITLE
Detailed How To

### ISSUE THREAD

**Issue by Roninside** [romeno-moreno/mxmrig#3]
Hi, thank you very much for your code.
I'd need more detailed steps about how to create the xcode project and integrate your code. It seems I'm missing some not-so-obvious-to-me parts of the process and I'm already stuck after downloading your code.

**Comment by Izder456** [comment]
> Hi, thank you very much for your code.
> 
> I'd need more detailed steps about how to create the xcode project and integrate your code. It seems I'm missing some not-so-obvious-to-me parts of the process and I'm already stuck after downloading your code.
> 
> 

Have you tried the releases tab on this repo? You don't need to compile it, if you don't want to.

If you want to compile it, you're out of luck because the "How To" assumes background knowledge on XCode, that I don't have.

(I am not the dev, just the main dev never responded, and I thought I'd give some sort of response)

**Comment by romeno-moreno** [comment]
Unfortunately, I'm no longer supporting the project and no new versions or updates will be released 😞
